name: GitHub Classroom Workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run autograding
        uses: education/autograding@v1

      - name: Generate test report
        if: always()
        run: |
          echo "=== Test Report ===" > test_report.txt
          echo "Build Status: $(if [ -f bin/test_validation ]; then echo 'SUCCESS'; else echo 'FAILED'; fi)" >> test_report.txt
          echo "Test Results: $(if [ -f bin/test_validation ] && bin/test_validation 2>&1 | grep -q 'ALL TESTS PASSED'; then echo 'ALL PASSED'; else echo 'SOME FAILED'; fi)" >> test_report.txt
          echo "Timestamp: $(date)" >> test_report.txt
          cat test_report.txt

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            bin/
            test_report.txt

